package io.schemat.displaykit.pack

import java.io.ByteArrayInputStream
import java.nio.charset.StandardCharsets
import java.util.concurrent.ConcurrentHashMap
import java.util.zip.ZipInputStream

/**
 * Asset provider that stores raw resource pack entries from item model ZIPs
 * generated by nucleation. Models accumulate in-memory and reset on restart.
 *
 * Handles merging item definition files across
 * multiple models so their custom_model_data cases coexist.
 */
object ItemModelAssetProvider : AssetProvider {

    // model name -> (zip entry path -> bytes)
    private val models = ConcurrentHashMap<String, Map<String, ByteArray>>()

    // model name -> item type (e.g. "paper", "leather_helmet")
    private val modelItems = ConcurrentHashMap<String, String>()

    /**
     * Extract ZIP entries from an item model resource pack ZIP and store them.
     * Skips pack.mcmeta since the main pack builder adds its own.
     */
    fun addModel(name: String, zipBytes: ByteArray, item: String = "paper") {
        modelItems[name] = item
        val entries = mutableMapOf<String, ByteArray>()
        ZipInputStream(ByteArrayInputStream(zipBytes)).use { zis ->
            var entry = zis.nextEntry
            while (entry != null) {
                if (!entry.isDirectory && entry.name != "pack.mcmeta") {
                    entries[entry.name] = zis.readAllBytes()
                }
                zis.closeEntry()
                entry = zis.nextEntry
            }
        }
        models[name] = entries
    }

    fun removeModel(name: String) {
        models.remove(name)
        modelItems.remove(name)
    }

    fun getModelNames(): Set<String> = models.keys.toSet()

    fun getModelItem(name: String): String? = modelItems[name]

    override fun contributeAssets(builder: PackBuilder) {
        // Collect item definition files separately for merging
        val itemDefs = mutableMapOf<String, MutableList<String>>()

        for ((_, entries) in models) {
            for ((path, bytes) in entries) {
                if (path.startsWith("assets/minecraft/items/") && path.endsWith(".json")) {
                    itemDefs.getOrPut(path) { mutableListOf() }.add(String(bytes, StandardCharsets.UTF_8))
                } else {
                    builder.addRaw(path, bytes)
                }
            }
        }

        // Merge item definitions by combining their cases arrays
        for ((path, jsonList) in itemDefs) {
            if (jsonList.size == 1) {
                builder.addRaw(path, jsonList[0].toByteArray(StandardCharsets.UTF_8))
            } else {
                val merged = mergeItemDefinitions(jsonList)
                builder.addRaw(path, merged.toByteArray(StandardCharsets.UTF_8))
            }
        }
    }

    /**
     * Merge multiple item definition JSONs by combining their "cases" arrays.
     *
     * Nucleation generates:
     * { "model": { "type": "minecraft:select", "property": "minecraft:custom_model_data",
     *   "fallback": { "type": "minecraft:model", "model": "minecraft:item/paper" },
     *   "cases": [ { "when": "name", "model": { ... } } ] } }
     *
     * We extract individual case objects from each JSON's cases array and combine them.
     */
    private fun mergeItemDefinitions(jsonList: List<String>): String {
        val allCases = mutableListOf<String>()

        for (json in jsonList) {
            // Find the cases array and extract individual case objects
            val casesStart = json.indexOf("\"cases\"")
            if (casesStart == -1) continue

            val arrayStart = json.indexOf('[', casesStart)
            if (arrayStart == -1) continue

            // Find matching close bracket, tracking nesting
            var depth = 0
            var i = arrayStart
            val arrayContent = StringBuilder()
            while (i < json.length) {
                val c = json[i]
                if (c == '[') depth++
                else if (c == ']') {
                    depth--
                    if (depth == 0) break
                }
                if (depth == 1 && c != '[') arrayContent.append(c)
                else if (depth > 1) arrayContent.append(c)
                i++
            }

            val content = arrayContent.toString().trim()
            if (content.isNotEmpty()) {
                allCases.add(content)
            }
        }

        // Extract fallback from first JSON
        val firstJson = jsonList[0]
        val fallbackStart = firstJson.indexOf("\"fallback\"")
        var fallback = """{ "type": "minecraft:model", "model": "minecraft:item/paper" }"""
        if (fallbackStart != -1) {
            val objStart = firstJson.indexOf('{', fallbackStart + 10)
            if (objStart != -1) {
                var depth = 0
                var i = objStart
                while (i < firstJson.length) {
                    if (firstJson[i] == '{') depth++
                    else if (firstJson[i] == '}') {
                        depth--
                        if (depth == 0) {
                            fallback = firstJson.substring(objStart, i + 1)
                            break
                        }
                    }
                    i++
                }
            }
        }

        return """{
  "model": {
    "type": "minecraft:select",
    "property": "minecraft:custom_model_data",
    "fallback": $fallback,
    "cases": [${allCases.joinToString(", ")}]
  }
}"""
    }
}
