package io.schemat.displaykit.pack

import java.io.ByteArrayInputStream
import java.nio.charset.StandardCharsets
import java.util.concurrent.ConcurrentHashMap
import java.util.zip.ZipInputStream

/**
 * Asset provider that stores raw resource pack entries from item model ZIPs
 * generated by nucleation. Models accumulate in-memory and reset on restart.
 *
 * Handles merging item definition files across
 * multiple models so their custom_model_data cases coexist.
 */
object ItemModelAssetProvider : AssetProvider {

    // model name -> (zip entry path -> bytes)
    private val models = ConcurrentHashMap<String, Map<String, ByteArray>>()

    // model name -> item type (e.g. "paper", "leather_helmet")
    private val modelItems = ConcurrentHashMap<String, String>()

    /**
     * Extract ZIP entries from an item model resource pack ZIP and store them.
     * Skips pack.mcmeta since the main pack builder adds its own.
     */
    fun addModel(name: String, zipBytes: ByteArray, item: String = "paper") {
        modelItems[name] = item
        val entries = mutableMapOf<String, ByteArray>()
        ZipInputStream(ByteArrayInputStream(zipBytes)).use { zis ->
            var entry = zis.nextEntry
            while (entry != null) {
                if (!entry.isDirectory && entry.name != "pack.mcmeta") {
                    entries[entry.name] = zis.readAllBytes()
                }
                zis.closeEntry()
                entry = zis.nextEntry
            }
        }
        models[name] = entries
    }

    fun removeModel(name: String) {
        models.remove(name)
        modelItems.remove(name)
    }

    fun getModelNames(): Set<String> = models.keys.toSet()

    fun getModelItem(name: String): String? = modelItems[name]

    /**
     * Item definitions go through [PackBuilder.addItemDefinition], which owns
     * the merge. That is what lets `SpriteSolidProvider` add its own
     * CustomModelData cases to the same `leather_horse_armor` definition
     * without either provider clobbering the other, whichever runs first.
     */
    override fun contributeAssets(builder: PackBuilder) {
        for ((_, entries) in models) {
            for ((path, bytes) in entries) {
                if (isItemDefinition(path)) {
                    builder.addItemDefinition(path, String(bytes, StandardCharsets.UTF_8))
                } else {
                    builder.addRaw(path, bytes)
                }
            }
        }
    }

    private fun isItemDefinition(path: String): Boolean =
        path.startsWith("assets/minecraft/items/") && path.endsWith(".json")
}
