package io.schemat.displaykit.pack

import com.google.gson.JsonArray
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import io.schemat.displaykit.sprite.SpriteGlyphs
import io.schemat.displaykit.sprite.SpriteId

/** One committed crop of a nine-sliced sprite. */
data class CatalogCrop(
    val x: Int, val y: Int, val w: Int, val h: Int,
    val resource: String
)

/**
 * The committed nine-slice crops, read from the pack module's own resources.
 *
 * Generated by `:libs:displaykit:pack:generateSpriteSlices`. Loaded once,
 * lazily.
 *
 * The catalogue is pure geometry and carries no codepoint. A crop needs one
 * codepoint *per vertical offset it is drawn at* — its `ascent` is baked per
 * font-provider entry — so allocation belongs to [SpriteSliceProvider], which
 * knows the offsets actually asked for, not to load time, which cannot.
 */
object SliceCatalog {

    private const val DIR = "/displaykit/slices"

    private val byId: Map<SpriteId, List<CatalogCrop>> by lazy { load() }

    fun regionsFor(id: SpriteId): List<CatalogCrop>? = byId[id]

    fun all(): Map<SpriteId, List<CatalogCrop>> = byId

    private fun load(): Map<SpriteId, List<CatalogCrop>> {
        val stream = SliceCatalog::class.java.getResourceAsStream("$DIR/manifest.json")
            ?: return emptyMap()
        val root = stream.bufferedReader().use { JsonParser.parseString(it.readText()).asJsonObject }
        val out = LinkedHashMap<SpriteId, List<CatalogCrop>>()
        for (s in root.getAsJsonArray("sprites")) {
            val o = s.asJsonObject
            val id = SpriteId(o.get("atlas").asString, o.get("sprite").asString)
            out[id] = o.getAsJsonArray("crops").map { c ->
                val co = c.asJsonObject
                CatalogCrop(
                    x = co.get("x").asInt, y = co.get("y").asInt,
                    w = co.get("w").asInt, h = co.get("h").asInt,
                    resource = co.get("file").asString
                )
            }
        }
        return out
    }

    fun resourceBytes(resource: String): ByteArray? =
        SliceCatalog::class.java.getResourceAsStream("$DIR/$resource")?.use { it.readBytes() }
}

/**
 * Ships the crops a server actually uses, plus the font providers that map
 * their codepoints.
 *
 * These are the only image bytes DisplayKit ships — everything else references
 * vanilla textures the client already has. Emission is on demand, so a pack
 * carries only the chrome in use.
 */
object SpriteSliceProvider : AssetProvider {

    /**
     * One crop at one vertical offset — the unit a font provider entry maps.
     *
     * The exact analogue of `SpriteGlyphs.GlyphVariant` for cropped regions.
     */
    data class SliceVariant(
        val id: SpriteId,
        val crop: CatalogCrop,
        val yOffset: Int,
        val codepoint: Int
    )

    private data class Key(val id: SpriteId, val srcX: Int, val srcY: Int, val yOffset: Int)

    private val requested = LinkedHashSet<SpriteId>()
    private val variants = LinkedHashMap<Key, SliceVariant>()

    /** Queue a sprite's crops for the next pack build. Idempotent. */
    fun request(id: SpriteId) {
        if (SliceCatalog.regionsFor(id) != null) requested.add(id)
    }

    /**
     * Codepoint for the crop at (srcX, srcY) drawn at [yOffset], allocating one
     * if this variant is new.
     *
     * Allocation is on demand and the mapping is append-only: a variant keeps
     * its codepoint for the life of the process, so a client that already
     * downloaded the pack never finds a character re-pointed underneath it.
     *
     * @throws IllegalArgumentException if [yOffset] is positive — the same
     *   constraint `SpriteGlyphs.codepointFor` enforces, since `ascent` is
     *   already at its maximum (`height`) at offset zero.
     */
    fun codepointFor(id: SpriteId, srcX: Int, srcY: Int, yOffset: Int): Int? {
        require(yOffset <= 0) {
            "Slice crop ($srcX,$srcY) of $id requested yOffset $yOffset, but positive " +
                "offsets are not representable — ascent <= height is client-enforced " +
                "and ascent already sits at its maximum when yOffset = 0."
        }
        val crop = SliceCatalog.regionsFor(id)?.firstOrNull { it.x == srcX && it.y == srcY }
            ?: return null
        return variants.getOrPut(Key(id, srcX, srcY, yOffset)) {
            SliceVariant(id, crop, yOffset, SpriteGlyphs.allocateSlice())
        }.codepoint
    }

    fun requestedIds(): Set<SpriteId> = requested.toSet()

    /** Every (crop, yOffset) variant allocated so far, in allocation order. */
    fun variants(): List<SliceVariant> = variants.values.toList()

    /**
     * How many variants have been allocated.
     *
     * Callers watch this across a repaint to decide whether the pack gained
     * glyphs the client has not seen — see `PickerWindow`.
     */
    fun variantCount(): Int = variants.size

    fun clear() {
        requested.clear()
        variants.clear()
    }

    override fun contributeAssets(builder: PackBuilder) {
        if (requested.isEmpty()) return

        // Crop images ship per requested sprite: a variant only ever re-points
        // at a crop the sprite already owns, so the image set does not grow
        // with the offsets in use.
        for (id in requested) {
            for (c in SliceCatalog.regionsFor(id) ?: continue) {
                val bytes = SliceCatalog.resourceBytes(c.resource) ?: continue
                builder.addRaw("assets/displaykit/textures/font/slices/${c.resource}", bytes)
            }
        }

        // Font providers ship per VARIANT, not per crop: `ascent` is baked into
        // the entry, so each vertical offset needs its own.
        val providers = JsonArray()
        for (v in variants.values) {
            if (v.id !in requested) continue
            if (SliceCatalog.resourceBytes(v.crop.resource) == null) continue
            providers.add(JsonObject().apply {
                addProperty("type", "bitmap")
                addProperty("file", "displaykit:font/slices/${v.crop.resource}")
                addProperty("height", v.crop.h)
                addProperty("ascent", v.crop.h + v.yOffset)
                add("chars", JsonArray().apply {
                    add(String(Character.toChars(v.codepoint)))
                })
            })
        }

        builder.addJson(
            "assets/displaykit/font/sprite_slices.json",
            JsonObject().apply { add("providers", providers) }.toString()
        )
    }
}
