package io.schemat.displaykit.pack

import com.google.gson.JsonArray
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import io.schemat.displaykit.sprite.SpriteGlyphs
import io.schemat.displaykit.sprite.SpriteId

/** One committed crop of a nine-sliced sprite. */
data class CatalogCrop(
    val x: Int, val y: Int, val w: Int, val h: Int,
    val resource: String,
    val codepoint: Int
)

/**
 * The committed nine-slice crops, read from the pack module's own resources.
 *
 * Generated by `:libs:displaykit:pack:generateSpriteSlices`. Loaded once,
 * lazily; codepoints are assigned at load so a given crop keeps the same
 * character for the life of the process.
 */
object SliceCatalog {

    private const val DIR = "/displaykit/slices"

    private val byId: Map<SpriteId, List<CatalogCrop>> by lazy { load() }

    fun regionsFor(id: SpriteId): List<CatalogCrop>? = byId[id]

    fun all(): Map<SpriteId, List<CatalogCrop>> = byId

    private fun load(): Map<SpriteId, List<CatalogCrop>> {
        val stream = SliceCatalog::class.java.getResourceAsStream("$DIR/manifest.json")
            ?: return emptyMap()
        val root = stream.bufferedReader().use { JsonParser.parseString(it.readText()).asJsonObject }
        val out = LinkedHashMap<SpriteId, List<CatalogCrop>>()
        for (s in root.getAsJsonArray("sprites")) {
            val o = s.asJsonObject
            val id = SpriteId(o.get("atlas").asString, o.get("sprite").asString)
            out[id] = o.getAsJsonArray("crops").map { c ->
                val co = c.asJsonObject
                CatalogCrop(
                    x = co.get("x").asInt, y = co.get("y").asInt,
                    w = co.get("w").asInt, h = co.get("h").asInt,
                    resource = co.get("file").asString,
                    codepoint = SpriteGlyphs.allocateSlice()
                )
            }
        }
        return out
    }

    fun resourceBytes(resource: String): ByteArray? =
        SliceCatalog::class.java.getResourceAsStream("$DIR/$resource")?.use { it.readBytes() }
}

/**
 * Ships the crops a server actually uses, plus the font providers that map
 * their codepoints.
 *
 * These are the only image bytes DisplayKit ships — everything else references
 * vanilla textures the client already has. Emission is on demand, so a pack
 * carries only the chrome in use.
 */
object SpriteSliceProvider : AssetProvider {

    private val requested = LinkedHashSet<SpriteId>()

    /** Queue a sprite's crops for the next pack build. Idempotent. */
    fun request(id: SpriteId) {
        if (SliceCatalog.regionsFor(id) != null) requested.add(id)
    }

    fun codepointFor(id: SpriteId, srcX: Int, srcY: Int): Int? =
        SliceCatalog.regionsFor(id)?.firstOrNull { it.x == srcX && it.y == srcY }?.codepoint

    fun requestedIds(): Set<SpriteId> = requested.toSet()

    fun clear() = requested.clear()

    override fun contributeAssets(builder: PackBuilder) {
        if (requested.isEmpty()) return
        val providers = JsonArray()
        for (id in requested) {
            for (c in SliceCatalog.regionsFor(id) ?: continue) {
                val bytes = SliceCatalog.resourceBytes(c.resource) ?: continue
                builder.addRaw("assets/displaykit/textures/font/slices/${c.resource}", bytes)
                providers.add(JsonObject().apply {
                    addProperty("type", "bitmap")
                    addProperty("file", "displaykit:font/slices/${c.resource}")
                    addProperty("height", c.h)
                    addProperty("ascent", c.h)
                    add("chars", JsonArray().apply {
                        add(String(Character.toChars(c.codepoint)))
                    })
                })
            }
        }
        builder.addJson(
            "assets/displaykit/font/sprite_slices.json",
            JsonObject().apply { add("providers", providers) }.toString()
        )
    }
}
